# This file was generated by GoReleaser. DO NOT EDIT.
cask "env0" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "77eeac22890599a12f0bb0ca45d4962db663fa4fb5186c43d42f3f42a00ce719"
      url "https://github.com/env0/homebrew-tap/releases/download/cli-v#{version}/env0_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "13fb62fc362e5d80e96d409892a1a0ab54860f05de2aadbc98912f1f284cb75b"
      url "https://github.com/env0/homebrew-tap/releases/download/cli-v#{version}/env0_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "acf06462cd5589895bdd91f012da7e11e6c1f33b04714be7031fd69cf3db3f23"
      url "https://github.com/env0/homebrew-tap/releases/download/cli-v#{version}/env0_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e851e9e00d4edac181f882f9de180f313868a0e90dc29dfec65f2d5060f0ef4b"
      url "https://github.com/env0/homebrew-tap/releases/download/cli-v#{version}/env0_#{version}_linux_arm64.tar.gz"
    end
  end

  name "env0"
  desc "The env0 CLI"
  homepage "https://www.env0.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "env0"

  # No zap stanza required

end
