# This file was generated by GoReleaser. DO NOT EDIT.
cask "env0" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "b4296d0b73bad8b65880a531d9f174c02677af9d7125a75f042f8daec586d660"
      url "https://github.com/env0/integrations/releases/download/cli-v#{version}/env0_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0d3c58ada6d4f2d6493ab0ffd19e628cda8305db2ac6e9e362320216456684a4"
      url "https://github.com/env0/integrations/releases/download/cli-v#{version}/env0_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1982d64b1553d985f37a91cebeaeec95b5b811f4aee6a7b3345348f0ff464159"
      url "https://github.com/env0/integrations/releases/download/cli-v#{version}/env0_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e4a36a9fce9a1f3ddeaf5dd4671499ff43d6e9f61229c1928312a902cc39597e"
      url "https://github.com/env0/integrations/releases/download/cli-v#{version}/env0_#{version}_linux_arm64.tar.gz"
    end
  end

  name "env0"
  desc "The env0 CLI"
  homepage "https://www.env0.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "env0"

  # No zap stanza required

end
